# Generated by Django 5.0.3 on 2024-03-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Материал')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание материала')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='self_study/', verbose_name='Превью-материал')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания материала')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Раздел')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание раздела')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='self_study/', verbose_name='Превью-раздел')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
    ]
