# Generated by Django 5.0.3 on 2024-03-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_study', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_test', models.CharField(blank=True, max_length=300, null=True, verbose_name='Тест материала')),
                ('material_test_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ на тест материала')),
            ],
            options={
                'verbose_name': 'Тест материала',
                'verbose_name_plural': 'Тесты материалов',
            },
        ),
    ]
