# Generated by Django 5.0.3 on 2024-03-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_study', '0003_materialstest'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='material_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='self_study.materialstest', verbose_name='Тест материала'),
        ),
    ]
